import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import Input from '../components/Input'
import Sidebar from '../components/Sidebar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="https://abs.twimg.com/favicons/favicon.ico"></link>
      </Head>
         
      <main className="flex min-h-screen mx-auto bg-gradient-to-r from-slate-50 to-slate-200">
        {/* Sidebar */}
        <Sidebar />

        {/* Feed */}
         <Feed/>
        

        {/* Widgets */}
        
        

        {/* Modal */}

        
      </main>
        
    </div>
  )
}
